name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: skilaverkefni-2/skilaverkefni-1

      - name: Run Vitest
        run: npm run test
        working-directory: skilaverkefni-2/skilaverkefni-1

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: skilaverkefni-2/skilaverkefni-1

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: skilaverkefni-2/skilaverkefni-1
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60